In [1]:
import numpy as np 

In [71]:
mat1=np.random.randint(10,size=(12,12))

In [72]:
mat2=np.random.randint(2,size=(3,3))
mat2

array([[0, 0, 1],
       [1, 0, 1],
       [1, 1, 0]])

In [73]:
mat1,mat2

(array([[6, 7, 2, 4, 4, 6, 1, 3, 7, 3, 4, 6],
        [4, 6, 1, 3, 1, 3, 3, 5, 7, 4, 2, 5],
        [0, 6, 7, 1, 6, 3, 1, 6, 1, 0, 2, 9],
        [5, 2, 5, 4, 3, 3, 8, 1, 2, 1, 1, 4],
        [9, 5, 5, 7, 9, 6, 6, 0, 7, 2, 4, 0],
        [0, 2, 6, 1, 2, 4, 4, 6, 1, 3, 7, 7],
        [0, 0, 3, 3, 9, 7, 5, 3, 0, 5, 9, 3],
        [2, 9, 1, 8, 7, 0, 0, 6, 3, 5, 3, 2],
        [5, 7, 6, 8, 6, 7, 7, 0, 9, 0, 9, 3],
        [4, 0, 5, 4, 8, 4, 6, 0, 5, 5, 0, 3],
        [1, 9, 1, 8, 5, 3, 2, 5, 3, 8, 2, 7],
        [0, 1, 1, 1, 0, 1, 4, 5, 6, 5, 4, 1]]),
 array([[0, 0, 1],
        [1, 0, 1],
        [1, 1, 0]]))

In [49]:
sub_range=[]
conv_filter = len(mat2)
iter = 0
for i in range(len(mat1)):
    sub_range.append((iter,iter+conv_filter))
    iter += 1

In [50]:
sub_range

[(0, 3), (1, 4), (2, 5), (3, 6), (4, 7), (5, 8)]

In [51]:
temp = []
for x in sub_range:
    if(x[0]<len(mat1) and x[1]<=len(mat1)):
        temp.append(x)

In [52]:
sub_range = temp
sub_range

[(0, 3), (1, 4), (2, 5), (3, 6)]

In [53]:
sub_mat = []

for col in sub_range:
    for row in sub_range:
        sub_mat.append(mat1[row[0]:row[1],col[0]:col[1]])

In [ ]:
sub_mat

In [57]:
sum = 0
for i in range(len(sub_mat)):
    sum += np.dot(sub_mat[i],mat2)
sum

array([[ 80,  80, 160],
       [ 80,  80, 158],
       [ 85,  85, 164]])

In [61]:
def convolute(parent,conv_filter):
    sub_range=[]
    sub_mat = []
    temp = []
    sum = 0
    
    conv_filter = len(conv_filter)
    iter = 0
    for i in range(len(parent)):
        sub_range.append((iter,iter+conv_filter))
        iter += 1
    
    for x in sub_range:
        if(x[0]<len(mat1) and x[1]<=len(mat1)):
            temp.append(x)
    sub_range = temp
    
    for col in sub_range:
        for row in sub_range:
            sub_mat.append([mat1[row[0]:row[1],col[0]:col[1]]])
    
    for i in range(len(sub_mat)):
        sum += np.dot(sub_mat[i],mat2)
        
    return sum    
    

In [74]:
convolute(mat1,mat2)

array([[[814, 406, 810],
        [823, 410, 817],
        [810, 404, 797]]])